// Code generated by ./cmd/genop.go; DO NOT EDIT.
//go:generate go run ./cmd/genop.go 
package vm

import "fmt"

func ToInt(value any) int {
    switch v := value.(type) {
    case int:
        return v
    case int8:
        return int(v)
    case int16:
        return int(v)
    case int32:
        return int(v)
    case int64:
        return int(v)
    case uint:
        return int(v)
    case uint8:
        return int(v)
    case uint16:
        return int(v)
    case uint32:
        return int(v)
    case uint64:
        return int(v)
    case uintptr:
        return int(v)
    case float32:
        return int(v)
    case float64:
        return int(v)
    default:
        panic(fmt.Sprintf("ToInt: unsupport %T", value))
    }
}

func ToInt8(value any) int8 {
    switch v := value.(type) {
    case int8:
        return v
    case int:
        return int8(v)
    case int16:
        return int8(v)
    case int32:
        return int8(v)
    case int64:
        return int8(v)
    case uint:
        return int8(v)
    case uint8:
        return int8(v)
    case uint16:
        return int8(v)
    case uint32:
        return int8(v)
    case uint64:
        return int8(v)
    case uintptr:
        return int8(v)
    case float32:
        return int8(v)
    case float64:
        return int8(v)
    default:
        panic(fmt.Sprintf("ToInt8: unsupport %T", value))
    }
}

func ToInt16(value any) int16 {
    switch v := value.(type) {
    case int16:
        return v
    case int:
        return int16(v)
    case int8:
        return int16(v)
    case int32:
        return int16(v)
    case int64:
        return int16(v)
    case uint:
        return int16(v)
    case uint8:
        return int16(v)
    case uint16:
        return int16(v)
    case uint32:
        return int16(v)
    case uint64:
        return int16(v)
    case uintptr:
        return int16(v)
    case float32:
        return int16(v)
    case float64:
        return int16(v)
    default:
        panic(fmt.Sprintf("ToInt16: unsupport %T", value))
    }
}

func ToInt32(value any) int32 {
    switch v := value.(type) {
    case int32:
        return v
    case int:
        return int32(v)
    case int8:
        return int32(v)
    case int16:
        return int32(v)
    case int64:
        return int32(v)
    case uint:
        return int32(v)
    case uint8:
        return int32(v)
    case uint16:
        return int32(v)
    case uint32:
        return int32(v)
    case uint64:
        return int32(v)
    case uintptr:
        return int32(v)
    case float32:
        return int32(v)
    case float64:
        return int32(v)
    default:
        panic(fmt.Sprintf("ToInt32: unsupport %T", value))
    }
}

func ToInt64(value any) int64 {
    switch v := value.(type) {
    case int64:
        return v
    case int:
        return int64(v)
    case int8:
        return int64(v)
    case int16:
        return int64(v)
    case int32:
        return int64(v)
    case uint:
        return int64(v)
    case uint8:
        return int64(v)
    case uint16:
        return int64(v)
    case uint32:
        return int64(v)
    case uint64:
        return int64(v)
    case uintptr:
        return int64(v)
    case float32:
        return int64(v)
    case float64:
        return int64(v)
    default:
        panic(fmt.Sprintf("ToInt64: unsupport %T", value))
    }
}

func ToUint(value any) uint {
    switch v := value.(type) {
    case uint:
        return v
    case int:
        return uint(v)
    case int8:
        return uint(v)
    case int16:
        return uint(v)
    case int32:
        return uint(v)
    case int64:
        return uint(v)
    case uint8:
        return uint(v)
    case uint16:
        return uint(v)
    case uint32:
        return uint(v)
    case uint64:
        return uint(v)
    case uintptr:
        return uint(v)
    case float32:
        return uint(v)
    case float64:
        return uint(v)
    default:
        panic(fmt.Sprintf("ToUint: unsupport %T", value))
    }
}

func ToUint8(value any) uint8 {
    switch v := value.(type) {
    case uint8:
        return v
    case int:
        return uint8(v)
    case int8:
        return uint8(v)
    case int16:
        return uint8(v)
    case int32:
        return uint8(v)
    case int64:
        return uint8(v)
    case uint:
        return uint8(v)
    case uint16:
        return uint8(v)
    case uint32:
        return uint8(v)
    case uint64:
        return uint8(v)
    case uintptr:
        return uint8(v)
    case float32:
        return uint8(v)
    case float64:
        return uint8(v)
    default:
        panic(fmt.Sprintf("ToUint8: unsupport %T", value))
    }
}

func ToUint16(value any) uint16 {
    switch v := value.(type) {
    case uint16:
        return v
    case int:
        return uint16(v)
    case int8:
        return uint16(v)
    case int16:
        return uint16(v)
    case int32:
        return uint16(v)
    case int64:
        return uint16(v)
    case uint:
        return uint16(v)
    case uint8:
        return uint16(v)
    case uint32:
        return uint16(v)
    case uint64:
        return uint16(v)
    case uintptr:
        return uint16(v)
    case float32:
        return uint16(v)
    case float64:
        return uint16(v)
    default:
        panic(fmt.Sprintf("ToUint16: unsupport %T", value))
    }
}

func ToUint32(value any) uint32 {
    switch v := value.(type) {
    case uint32:
        return v
    case int:
        return uint32(v)
    case int8:
        return uint32(v)
    case int16:
        return uint32(v)
    case int32:
        return uint32(v)
    case int64:
        return uint32(v)
    case uint:
        return uint32(v)
    case uint8:
        return uint32(v)
    case uint16:
        return uint32(v)
    case uint64:
        return uint32(v)
    case uintptr:
        return uint32(v)
    case float32:
        return uint32(v)
    case float64:
        return uint32(v)
    default:
        panic(fmt.Sprintf("ToUint32: unsupport %T", value))
    }
}

func ToUint64(value any) uint64 {
    switch v := value.(type) {
    case uint64:
        return v
    case int:
        return uint64(v)
    case int8:
        return uint64(v)
    case int16:
        return uint64(v)
    case int32:
        return uint64(v)
    case int64:
        return uint64(v)
    case uint:
        return uint64(v)
    case uint8:
        return uint64(v)
    case uint16:
        return uint64(v)
    case uint32:
        return uint64(v)
    case uintptr:
        return uint64(v)
    case float32:
        return uint64(v)
    case float64:
        return uint64(v)
    default:
        panic(fmt.Sprintf("ToUint64: unsupport %T", value))
    }
}

func ToUintptr(value any) uintptr {
    switch v := value.(type) {
    case uintptr:
        return v
    case int:
        return uintptr(v)
    case int8:
        return uintptr(v)
    case int16:
        return uintptr(v)
    case int32:
        return uintptr(v)
    case int64:
        return uintptr(v)
    case uint:
        return uintptr(v)
    case uint8:
        return uintptr(v)
    case uint16:
        return uintptr(v)
    case uint32:
        return uintptr(v)
    case uint64:
        return uintptr(v)
    case float32:
        return uintptr(v)
    case float64:
        return uintptr(v)
    default:
        panic(fmt.Sprintf("ToUintptr: unsupport %T", value))
    }
}

func ToFloat32(value any) float32 {
    switch v := value.(type) {
    case float32:
        return v
    case int:
        return float32(v)
    case int8:
        return float32(v)
    case int16:
        return float32(v)
    case int32:
        return float32(v)
    case int64:
        return float32(v)
    case uint:
        return float32(v)
    case uint8:
        return float32(v)
    case uint16:
        return float32(v)
    case uint32:
        return float32(v)
    case uint64:
        return float32(v)
    case uintptr:
        return float32(v)
    case float64:
        return float32(v)
    default:
        panic(fmt.Sprintf("ToFloat32: unsupport %T", value))
    }
}

func ToFloat64(value any) float64 {
    switch v := value.(type) {
    case float64:
        return v
    case int:
        return float64(v)
    case int8:
        return float64(v)
    case int16:
        return float64(v)
    case int32:
        return float64(v)
    case int64:
        return float64(v)
    case uint:
        return float64(v)
    case uint8:
        return float64(v)
    case uint16:
        return float64(v)
    case uint32:
        return float64(v)
    case uint64:
        return float64(v)
    case uintptr:
        return float64(v)
    case float32:
        return float64(v)
    default:
        panic(fmt.Sprintf("ToFloat64: unsupport %T", value))
    }
}

