// Code generated by slice_converter_generator; DO NOT EDIT.
package vm

import "reflect"

func CopyToSlice(from []any, typ reflect.Type) (to any) {
	if typ.Kind() != reflect.Slice {
		panic("typ must be slice type")
	}
	elemKind := typ.Elem().Kind()
	switch elemKind {
	case reflect.Int:
		return ToIntSlice(from)
	case reflect.Int8:
		return ToInt8Slice(from)
	case reflect.Int16:
		return ToInt16Slice(from)
	case reflect.Int32:
		return ToInt32Slice(from)
	case reflect.Int64:
		return ToInt64Slice(from)
	case reflect.Uint:
		return ToUintSlice(from)
	case reflect.Uint8:
		return ToUint8Slice(from)
	case reflect.Uint16:
		return ToUint16Slice(from)
	case reflect.Uint32:
		return ToUint32Slice(from)
	case reflect.Uint64:
		return ToUint64Slice(from)
	case reflect.Uintptr:
		return ToUintptrSlice(from)
	case reflect.Float32:
		return ToFloat32Slice(from)
	case reflect.Float64:
		return ToFloat64Slice(from)
	default:
		// For unsupported types or interface{}, return original slice
		return from
	}
}

func CopyToSliceByKind(from []any, kind reflect.Kind) (to any) {
	switch kind {
	case reflect.Int:
		return ToIntSlice(from)
	case reflect.Int8:
		return ToInt8Slice(from)
	case reflect.Int16:
		return ToInt16Slice(from)
	case reflect.Int32:
		return ToInt32Slice(from)
	case reflect.Int64:
		return ToInt64Slice(from)
	case reflect.Uint:
		return ToUintSlice(from)
	case reflect.Uint8:
		return ToUint8Slice(from)
	case reflect.Uint16:
		return ToUint16Slice(from)
	case reflect.Uint32:
		return ToUint32Slice(from)
	case reflect.Uint64:
		return ToUint64Slice(from)
	case reflect.Uintptr:
		return ToUintptrSlice(from)
	case reflect.Float32:
		return ToFloat32Slice(from)
	case reflect.Float64:
		return ToFloat64Slice(from)
	case reflect.String:
		return ToStringSlice(from)
	default:
		// For unsupported types or interface{}, return original slice
		return from
	}
}

// ToStringSlice converts []any to []string
func ToStringSlice(s []any) []string {
	if s == nil {
		return nil
	}
	ret := make([]string, len(s))
	for i, v := range s {
		ret[i] = v.(string)
	}
	return ret
}

// ToIntSlice converts []any to []int
func ToIntSlice(s []any) []int {
	if s == nil {
		return nil
	}
	ret := make([]int, len(s))
	for i, v := range s {
		ret[i] = ToInt(v)
	}
	return ret
}

// ToInt8Slice converts []any to []int8
func ToInt8Slice(s []any) []int8 {
	if s == nil {
		return nil
	}
	ret := make([]int8, len(s))
	for i, v := range s {
		ret[i] = ToInt8(v)
	}
	return ret
}

// ToInt16Slice converts []any to []int16
func ToInt16Slice(s []any) []int16 {
	if s == nil {
		return nil
	}
	ret := make([]int16, len(s))
	for i, v := range s {
		ret[i] = ToInt16(v)
	}
	return ret
}

// ToInt32Slice converts []any to []int32
func ToInt32Slice(s []any) []int32 {
	if s == nil {
		return nil
	}
	ret := make([]int32, len(s))
	for i, v := range s {
		ret[i] = ToInt32(v)
	}
	return ret
}

// ToInt64Slice converts []any to []int64
func ToInt64Slice(s []any) []int64 {
	if s == nil {
		return nil
	}
	ret := make([]int64, len(s))
	for i, v := range s {
		ret[i] = ToInt64(v)
	}
	return ret
}

// ToUintSlice converts []any to []uint
func ToUintSlice(s []any) []uint {
	if s == nil {
		return nil
	}
	ret := make([]uint, len(s))
	for i, v := range s {
		ret[i] = ToUint(v)
	}
	return ret
}

// ToUint8Slice converts []any to []uint8
func ToUint8Slice(s []any) []uint8 {
	if s == nil {
		return nil
	}
	ret := make([]uint8, len(s))
	for i, v := range s {
		ret[i] = ToUint8(v)
	}
	return ret
}

// ToUint16Slice converts []any to []uint16
func ToUint16Slice(s []any) []uint16 {
	if s == nil {
		return nil
	}
	ret := make([]uint16, len(s))
	for i, v := range s {
		ret[i] = ToUint16(v)
	}
	return ret
}

// ToUint32Slice converts []any to []uint32
func ToUint32Slice(s []any) []uint32 {
	if s == nil {
		return nil
	}
	ret := make([]uint32, len(s))
	for i, v := range s {
		ret[i] = ToUint32(v)
	}
	return ret
}

// ToUint64Slice converts []any to []uint64
func ToUint64Slice(s []any) []uint64 {
	if s == nil {
		return nil
	}
	ret := make([]uint64, len(s))
	for i, v := range s {
		ret[i] = ToUint64(v)
	}
	return ret
}

// ToUintptrSlice converts []any to []uintptr
func ToUintptrSlice(s []any) []uintptr {
	if s == nil {
		return nil
	}
	ret := make([]uintptr, len(s))
	for i, v := range s {
		ret[i] = ToUintptr(v)
	}
	return ret
}

// ToFloat32Slice converts []any to []float32
func ToFloat32Slice(s []any) []float32 {
	if s == nil {
		return nil
	}
	ret := make([]float32, len(s))
	for i, v := range s {
		ret[i] = ToFloat32(v)
	}
	return ret
}

// ToFloat64Slice converts []any to []float64
func ToFloat64Slice(s []any) []float64 {
	if s == nil {
		return nil
	}
	ret := make([]float64, len(s))
	for i, v := range s {
		ret[i] = ToFloat64(v)
	}
	return ret
}
