package main

import (
	"fmt"
	"go/format"
	"os"
	"strings"
)

func main() {
	genOpFuncs()
	genToFuncs()
}

func genOpFuncs() {
	var sb strings.Builder

	sb.WriteString(`// Code generated by cmd/genop.go. DO NOT EDIT.
// go:generate go run ./cmd/genop.go 
package vm

import (
	"errors"
	"fmt"
	"reflect"
)

var (
	ErrDivisionByZero  = errors.New("Error: division by zero")
	ErrModuloByZero    = errors.New("Error: modulo by zero")
)

func eq(x, y any) bool {
	if x == nil {
		if y == nil {
			return true
		}
		ry := reflect.ValueOf(y)
		if ry.Kind() == reflect.Ptr && ry.IsNil() {
			return true
		}
	}
	if y == nil {
		rx := reflect.ValueOf(x)
		if rx.Kind() == reflect.Ptr && rx.IsNil() {
			return true
		}
	}
	return x == y
}

`)

	operations := []struct {
		name string
		op   string
	}{
		{"Add", "+"},
		{"Sub", "-"},
		{"Mul", "*"},
		{"Div", "/"},
		{"Mod", "%"},
		{"Eq", "=="},
		{"Lt", "<"},
		{"Gt", ">"},
		{"Gte", ">="},
		{"Lte", "<="},
		{"Neq", "!="},
		{"And", "&"},
		{"Or", "|"},
		{"Xor", "^"},
	}

	for _, op := range operations {
		sb.WriteString(generateOperationFunction(op.name, op.op))
		sb.WriteString("\n\n")
	}
	code := sb.String()
	formatted, err := format.Source([]byte(code))
	if err != nil {
		panic(err)
	}

	err = os.WriteFile("./vm/op.gen.go", formatted, 0644)
	if err != nil {
		panic(err)
	}

	fmt.Println("计算代码已生成到 ./vm/op.gen.go")
}

func generateOperationFunction(funcName, operator string) string {
	var sb strings.Builder

	// 根据操作符类型确定返回值类型
	returnType := "any"
	if isComparisonOperation(operator) {
		returnType = "bool"
	} else if isBitwiseOperation(operator) {
		returnType = "int"
	}

	sb.WriteString(fmt.Sprintf("// %s 执行 %s 运算\n", funcName, operator))
	sb.WriteString(fmt.Sprintf("func %s(x, y any) (%s, error) {\n", funcName, returnType))
	sb.WriteString("    switch xv := x.(type) {\n")

	// 整数类型
	intTypes := []string{"int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64"}
	for _, xt := range intTypes {
		sb.WriteString(fmt.Sprintf("    case %s:\n", xt))
		sb.WriteString("        switch yv := y.(type) {\n")

		// y 为整数类型
		for _, yt := range intTypes {
			sb.WriteString(fmt.Sprintf("        case %s:\n", yt))
			if operator == "/" {
				sb.WriteString("            if yv == 0 {\n")
				sb.WriteString("                var zero any\n")
				sb.WriteString("                return zero, ErrDivisionByZero\n")
				sb.WriteString("            }\n")
				if returnType == "int" {
					sb.WriteString(fmt.Sprintf("            return int(xv) %s int(yv), nil\n", operator))
				} else {
					sb.WriteString(fmt.Sprintf("            return int(xv) %s int(yv), nil\n", operator))
				}
			} else if operator == "%" {
				sb.WriteString("            if yv == 0 {\n")
				sb.WriteString("                return 0, ErrModuloByZero\n")
				sb.WriteString("            }\n")
				sb.WriteString(fmt.Sprintf("            return int(xv) %s int(yv), nil\n", operator))
			} else {
				if returnType == "bool" {
					sb.WriteString(fmt.Sprintf("            return int(xv) %s int(yv), nil\n", operator))
				} else if returnType == "int" {
					sb.WriteString(fmt.Sprintf("            return int(xv) %s int(yv), nil\n", operator))
				} else {
					sb.WriteString(fmt.Sprintf("            return int(xv) %s int(yv), nil\n", operator))
				}
			}
		}

		// y 为浮点类型
		if isFloatAllowed(operator) {
			floatTypes := []string{"float32", "float64"}
			for _, yt := range floatTypes {
				sb.WriteString(fmt.Sprintf("        case %s:\n", yt))
				if operator == "/" {
					sb.WriteString("            if yv == 0 {\n")
					sb.WriteString("                var zero any\n")
					sb.WriteString("                return zero, ErrDivisionByZero\n")
					sb.WriteString("            }\n")
				}
				if returnType == "bool" {
					sb.WriteString(fmt.Sprintf("            return float64(xv) %s float64(yv), nil\n", operator))
				} else {
					sb.WriteString(fmt.Sprintf("            return float64(xv) %s float64(yv), nil\n", operator))
				}
			}
		}

		sb.WriteString("        }\n")
	}

	// 浮点类型
	if isFloatAllowed(operator) {
		floatTypes := []string{"float32", "float64"}
		for _, xt := range floatTypes {
			sb.WriteString(fmt.Sprintf("    case %s:\n", xt))
			sb.WriteString("        switch yv := y.(type) {\n")

			// y 为整数类型
			for _, yt := range intTypes {
				sb.WriteString(fmt.Sprintf("        case %s:\n", yt))
				if operator == "/" {
					sb.WriteString("            if yv == 0 {\n")
					sb.WriteString("                var zero any\n")
					sb.WriteString("                return zero, ErrDivisionByZero\n")
					sb.WriteString("            }\n")
				}
				if returnType == "bool" {
					sb.WriteString(fmt.Sprintf("            return float64(xv) %s float64(yv), nil\n", operator))
				} else {
					sb.WriteString(fmt.Sprintf("            return float64(xv) %s float64(yv), nil\n", operator))
				}
			}

			// y 为浮点类型
			for _, yt := range floatTypes {
				sb.WriteString(fmt.Sprintf("        case %s:\n", yt))
				if operator == "/" {
					sb.WriteString("            if yv == 0 {\n")
					sb.WriteString("                var zero any\n")
					sb.WriteString("                return zero, ErrDivisionByZero\n")
					sb.WriteString("            }\n")
				}
				if returnType == "bool" {
					sb.WriteString(fmt.Sprintf("            return float64(xv) %s float64(yv), nil\n", operator))
				} else {
					sb.WriteString(fmt.Sprintf("            return float64(xv) %s float64(yv), nil\n", operator))
				}
			}

			sb.WriteString("        }\n")
		}
	}

	// 字符串类型
	if isStringAllowed(operator) {
		sb.WriteString("    case string:\n")
		sb.WriteString("        switch yv := y.(type) {\n")
		sb.WriteString("        case string:\n")

		switch operator {
		case "+":
			sb.WriteString("            return xv + yv, nil\n")
		case "==":
			sb.WriteString("            return xv == yv, nil\n")
		case "!=":
			sb.WriteString("            return xv != yv, nil\n")
		case "<":
			sb.WriteString("            return xv < yv, nil\n")
		case ">":
			sb.WriteString("            return xv > yv, nil\n")
		case "<=":
			sb.WriteString("            return xv <= yv, nil\n")
		case ">=":
			sb.WriteString("            return xv >= yv, nil\n")
		}

		sb.WriteString("        }\n")
	}

	// 统一错误返回
	sb.WriteString("    }\n")

	// 根据返回值类型返回适当的零值
	if funcName == "Eq" {
		sb.WriteString("    return eq(x, y), nil\n")
	} else {
		if returnType == "bool" {
			sb.WriteString("    return false, fmt.Errorf(\"unsupported operator: %T %s %T\", x, \"")
		} else if returnType == "int" {
			sb.WriteString("    return 0, fmt.Errorf(\"unsupported operator: %T %s %T\", x, \"")
		} else {
			sb.WriteString("    var zero any\n")
			sb.WriteString("    return zero, fmt.Errorf(\"unsupported operator: %T %s %T\", x, \"")
		}
		sb.WriteString(operator)
		sb.WriteString("\", y)\n")
	}

	sb.WriteString("}\n")

	return sb.String()
}

func isComparisonOperation(op string) bool {
	return op == "==" || op == "<" || op == ">" || op == ">=" || op == "<=" || op == "!="
}

func isBitwiseOperation(op string) bool {
	return op == "&" || op == "|" || op == "^" || op == "%"
}

func isFloatAllowed(op string) bool {
	// 位运算不允许浮点数
	bitwiseOps := map[string]bool{"&": true, "|": true, "^": true, "%": true}
	return !bitwiseOps[op]
}

func isStringAllowed(op string) bool {
	// 字符串只支持连接和比较运算
	stringOps := map[string]bool{
		"+": true, "==": true, "!=": true,
		"<": true, ">": true, "<=": true, ">=": true,
	}
	return stringOps[op]
}

func genToFuncs() {
	// 定义要生成的所有 int 和 float 类型
	intTypes := []string{
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
	}

	floatTypes := []string{
		"float32", "float64",
	}

	var sb strings.Builder

	// 写入文件头部
	sb.WriteString("// Code generated by ./cmd/genop.go; DO NOT EDIT.\n")
	sb.WriteString("//go:generate go run ./cmd/genop.go \n")
	sb.WriteString("package vm\n\n")
	sb.WriteString("import \"fmt\"\n\n")

	// 为每个 int 类型生成转换函数
	for _, intType := range intTypes {
		genToFuc(&sb, intType, intTypes, floatTypes)
	}

	// 为每个 float 类型生成转换函数
	for _, floatType := range floatTypes {
		genToFuc(&sb, floatType, intTypes, floatTypes)
	}

	// 写入文件
	err := os.WriteFile("./vm/to.gen.go", []byte(sb.String()), 0644)
	if err != nil {
		panic(err)
	}

	fmt.Println("tofunc代码生成至: ./vm/to.gen.go")
}

func genToFuc(sb *strings.Builder, targetType string, intTypes, floatTypes []string) {
	funcName := "To" + strings.Title(targetType)

	sb.WriteString(fmt.Sprintf("func %s(value any) %s {\n", funcName, targetType))
	sb.WriteString("    switch v := value.(type) {\n")

	// 目标类型本身的 case
	sb.WriteString(fmt.Sprintf("    case %s:\n", targetType))
	sb.WriteString("        return v\n")

	// 所有 int 类型的 case
	for _, intType := range intTypes {
		if intType != targetType {
			sb.WriteString(fmt.Sprintf("    case %s:\n", intType))
			sb.WriteString(fmt.Sprintf("        return %s(v)\n", targetType))
		}
	}

	// 所有 float 类型的 case
	for _, floatType := range floatTypes {
		if floatType != targetType {
			sb.WriteString(fmt.Sprintf("    case %s:\n", floatType))
			sb.WriteString(fmt.Sprintf("        return %s(v)\n", targetType))
		}
	}

	// default 情况
	sb.WriteString("    default:\n")
	sb.WriteString(fmt.Sprintf("        panic(fmt.Sprintf(\"%s: unsupport %%T\", value))\n", funcName))
	sb.WriteString("    }\n")
	sb.WriteString("}\n\n")
}
