package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"
)

func main() {
	genOpFuncs()
	genToFuncs()
	genToSliceFuncs()
}

var numberTypes = []string{
	"int", "int8", "int16", "int32", "int64",
	"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
	"float32", "float64",
}

// 模板数据
type TemplateData struct {
	ToType string
}

// 函数模板
const funcTemplate = `// To{{.ToType | Title}}Slice converts []any to []{{.ToType}}
func To{{.ToType | Title}}Slice(s []any) []{{.ToType}} {
	if s == nil {
		return nil
	}
	ret := make([]{{.ToType}}, len(s))
	for i, v := range s {
		ret[i] = To{{.ToType | Title}}(v)
	}
	return ret
}`

// 主文件模板
const fileTemplate = `// Code generated by slice_converter_generator; DO NOT EDIT.
package gen

import "reflect"

func CopyToSlice(from []any, typ reflect.Type) (to any) {
	if typ.Kind() != reflect.Slice {
		panic("typ must be slice type")
	}
	elemKind := typ.Elem().Kind()
	switch elemKind {
	case reflect.Int:
		return ToIntSlice(from)
	case reflect.Int8:
		return ToInt8Slice(from)
	case reflect.Int16:
		return ToInt16Slice(from)
	case reflect.Int32:
		return ToInt32Slice(from)
	case reflect.Int64:
		return ToInt64Slice(from)
	case reflect.Uint:
		return ToUintSlice(from)
	case reflect.Uint8:
		return ToUint8Slice(from)
	case reflect.Uint16:
		return ToUint16Slice(from)
	case reflect.Uint32:
		return ToUint32Slice(from)
	case reflect.Uint64:
		return ToUint64Slice(from)
	case reflect.Uintptr:
		return ToUintptrSlice(from)
	case reflect.Float32:
		return ToFloat32Slice(from)
	case reflect.Float64:
		return ToFloat64Slice(from)
	default:
		// For unsupported types or interface{}, return original slice
		return from
	}
}

func CopyToSliceByKind(from []any,kind reflect.Kind) (to any) {
	switch kind {
	case reflect.Int:
		return ToIntSlice(from)
	case reflect.Int8:
		return ToInt8Slice(from)
	case reflect.Int16:
		return ToInt16Slice(from)
	case reflect.Int32:
		return ToInt32Slice(from)
	case reflect.Int64:
		return ToInt64Slice(from)
	case reflect.Uint:
		return ToUintSlice(from)
	case reflect.Uint8:
		return ToUint8Slice(from)
	case reflect.Uint16:
		return ToUint16Slice(from)
	case reflect.Uint32:
		return ToUint32Slice(from)
	case reflect.Uint64:
		return ToUint64Slice(from)
	case reflect.Uintptr:
		return ToUintptrSlice(from)
	case reflect.Float32:
		return ToFloat32Slice(from)
	case reflect.Float64:
		return ToFloat64Slice(from)
	case reflect.String:
		return ToStringSlice(from)
	default:
		// For unsupported types or interface{}, return original slice
		return from
	}
}

// ToStringSlice converts []any to []string
func ToStringSlice(s []any) []string {
	if s == nil {
		return nil
	}
	ret := make([]string, len(s))
	for i, v := range s {
		ret[i] = v.(string)
	}
	return ret
}


{{range .Functions}}
{{.}}
{{end}}
`

func genToSliceFuncs() {

	var functions []string

	// 为所有目标类型生成从 []any 转换的函数
	for _, toType := range numberTypes {
		funcCode := generateSingleFunction(toType)
		functions = append(functions, funcCode)
	}

	// 生成完整的Go文件
	generateCompleteFile(functions)
}

func generateSingleFunction(toType string) string {
	// 创建模板函数映射
	funcMap := template.FuncMap{
		"Title": strings.Title,
	}

	// 解析模板
	tmpl, err := template.New("func").Funcs(funcMap).Parse(funcTemplate)
	if err != nil {
		panic(fmt.Sprintf("Failed to parse template: %v", err))
	}

	// 执行模板
	var buf bytes.Buffer
	data := TemplateData{
		ToType: toType,
	}

	err = tmpl.Execute(&buf, data)
	if err != nil {
		panic(fmt.Sprintf("Failed to execute template: %v", err))
	}

	return buf.String()
}

func generateCompleteFile(functions []string) {
	// 创建主模板
	tmpl, err := template.New("file").Parse(fileTemplate)
	if err != nil {
		panic(fmt.Sprintf("Failed to parse file template: %v", err))
	}

	// 准备数据
	data := struct {
		Functions []string
	}{
		Functions: functions,
	}

	// 执行模板
	var buf bytes.Buffer
	err = tmpl.Execute(&buf, data)
	if err != nil {
		panic(fmt.Sprintf("Failed to execute file template: %v", err))
	}

	// 格式化代码
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// 如果格式化失败，使用原始代码
		fmt.Printf("Warning: Formatting failed, using unformatted code: %v\n", err)
		formatted = buf.Bytes()
	}

	// 写入文件
	err = os.WriteFile("./gen/toslice.gen.go", formatted, 0644)
	if err != nil {
		panic(fmt.Sprintf("Failed to write file: %v", err))
	}

	fmt.Printf("Generated %d slice conversion functions from []any\n", len(functions))
}

func genOpFuncs() {
	var sb strings.Builder

	sb.WriteString(`// Code generated by cmd/genop.go. DO NOT EDIT.
// go:generate go run ./cmd/genop.go 
package gen

import (
	"errors"
	"fmt"
	"reflect"
)

var (
	ErrDivisionByZero  = errors.New("division by zero")
	ErrModuloByZero    = errors.New("modulo by zero")
)

func eq(x, y any) bool {
	if x == nil {
		if y == nil {
			return true
		}
		ry := reflect.ValueOf(y)
		return ry.IsNil()
	}
	if y == nil {
		rx := reflect.ValueOf(x)
		return rx.IsNil()
	}
	xt, yt := reflect.TypeOf(x), reflect.TypeOf(y)
	if xt != yt {
		panic(fmt.Sprintf("invalid operation '==' (mismatched types %T and %T)", x, y))
	}
	return x == y
}

`)

	operations := []struct {
		name string
		op   string
	}{
		{"Add", "+"},
		{"Sub", "-"},
		{"Mul", "*"},
		{"Div", "/"},
		{"Mod", "%"},
		{"LShift", "<<"},
		{"RShift", ">>"},
		{"Eq", "=="},
		{"Lt", "<"},
		{"Gt", ">"},
		{"Gte", ">="},
		{"Lte", "<="},
		{"Neq", "!="},
		{"And", "&"},
		{"Or", "|"},
		{"Xor", "^"},
	}

	for _, op := range operations {
		sb.WriteString(generateOperationFunction(op.name, op.op))
		sb.WriteString("\n\n")
	}
	code := sb.String()
	formatted, err := format.Source([]byte(code))
	if err != nil {
		panic(err)
	}

	err = os.WriteFile("./gen/op.gen.go", formatted, 0644)
	if err != nil {
		panic(err)
	}

	fmt.Println("计算代码已生成到 ./gen/op.gen.go")
}

func generateOperationFunction(funcName, operator string) string {
	var sb strings.Builder

	// 根据操作符类型确定返回值类型
	returnType := "any"
	if isComparisonOperation(operator) {
		returnType = "bool"
	} else if isBitwiseOperation(operator) {
		returnType = "int"
	}

	sb.WriteString(fmt.Sprintf("// %s 执行 %s 运算\n", funcName, operator))
	sb.WriteString(fmt.Sprintf("func %s(x, y any) (%s, error) {\n", funcName, returnType))
	sb.WriteString("    switch xv := x.(type) {\n")

	// 整数类型
	intTypes := []string{"int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64"}
	for _, xt := range intTypes {
		sb.WriteString(fmt.Sprintf("    case %s:\n", xt))
		sb.WriteString("        switch yv := y.(type) {\n")

		// y 为整数类型
		for _, yt := range intTypes {
			sb.WriteString(fmt.Sprintf("        case %s:\n", yt))
			if operator == "/" {
				sb.WriteString("            if yv == 0 {\n")
				sb.WriteString("                var zero any\n")
				sb.WriteString("                return zero, ErrDivisionByZero\n")
				sb.WriteString("            }\n")
				if returnType == "int" {
					sb.WriteString(fmt.Sprintf("            return int(xv) %s int(yv), nil\n", operator))
				} else {
					sb.WriteString(fmt.Sprintf("            return int(xv) %s int(yv), nil\n", operator))
				}
			} else if operator == "%" {
				sb.WriteString("            if yv == 0 {\n")
				sb.WriteString("                return 0, ErrModuloByZero\n")
				sb.WriteString("            }\n")
				sb.WriteString(fmt.Sprintf("            return int(xv) %s int(yv), nil\n", operator))
			} else {
				if returnType == "bool" {
					sb.WriteString(fmt.Sprintf("            return int(xv) %s int(yv), nil\n", operator))
				} else if returnType == "int" {
					sb.WriteString(fmt.Sprintf("            return int(xv) %s int(yv), nil\n", operator))
				} else {
					sb.WriteString(fmt.Sprintf("            return int(xv) %s int(yv), nil\n", operator))
				}
			}
		}

		// y 为浮点类型
		if isFloatAllowed(operator) {
			floatTypes := []string{"float32", "float64"}
			for _, yt := range floatTypes {
				sb.WriteString(fmt.Sprintf("        case %s:\n", yt))
				if operator == "/" {
					sb.WriteString("            if yv == 0 {\n")
					sb.WriteString("                var zero any\n")
					sb.WriteString("                return zero, ErrDivisionByZero\n")
					sb.WriteString("            }\n")
				}
				if returnType == "bool" {
					sb.WriteString(fmt.Sprintf("            return float64(xv) %s float64(yv), nil\n", operator))
				} else {
					sb.WriteString(fmt.Sprintf("            return float64(xv) %s float64(yv), nil\n", operator))
				}
			}
		}

		sb.WriteString("        }\n")
	}

	// 浮点类型
	if isFloatAllowed(operator) {
		floatTypes := []string{"float32", "float64"}
		for _, xt := range floatTypes {
			sb.WriteString(fmt.Sprintf("    case %s:\n", xt))
			sb.WriteString("        switch yv := y.(type) {\n")

			// y 为整数类型
			for _, yt := range intTypes {
				sb.WriteString(fmt.Sprintf("        case %s:\n", yt))
				if operator == "/" {
					sb.WriteString("            if yv == 0 {\n")
					sb.WriteString("                var zero any\n")
					sb.WriteString("                return zero, ErrDivisionByZero\n")
					sb.WriteString("            }\n")
				}
				if returnType == "bool" {
					sb.WriteString(fmt.Sprintf("            return float64(xv) %s float64(yv), nil\n", operator))
				} else {
					sb.WriteString(fmt.Sprintf("            return float64(xv) %s float64(yv), nil\n", operator))
				}
			}

			// y 为浮点类型
			for _, yt := range floatTypes {
				sb.WriteString(fmt.Sprintf("        case %s:\n", yt))
				if operator == "/" {
					sb.WriteString("            if yv == 0 {\n")
					sb.WriteString("                var zero any\n")
					sb.WriteString("                return zero, ErrDivisionByZero\n")
					sb.WriteString("            }\n")
				}
				if returnType == "bool" {
					sb.WriteString(fmt.Sprintf("            return float64(xv) %s float64(yv), nil\n", operator))
				} else {
					sb.WriteString(fmt.Sprintf("            return float64(xv) %s float64(yv), nil\n", operator))
				}
			}

			sb.WriteString("        }\n")
		}
	}

	// 字符串类型
	if isStringAllowed(operator) {
		sb.WriteString("    case string:\n")
		sb.WriteString("        switch yv := y.(type) {\n")
		sb.WriteString("        case string:\n")

		switch operator {
		case "+":
			sb.WriteString("            return xv + yv, nil\n")
		case "==":
			sb.WriteString("            return xv == yv, nil\n")
		case "!=":
			sb.WriteString("            return xv != yv, nil\n")
		case "<":
			sb.WriteString("            return xv < yv, nil\n")
		case ">":
			sb.WriteString("            return xv > yv, nil\n")
		case "<=":
			sb.WriteString("            return xv <= yv, nil\n")
		case ">=":
			sb.WriteString("            return xv >= yv, nil\n")
		}

		sb.WriteString("        }\n")
	}

	// 统一错误返回
	sb.WriteString("    }\n")

	// 根据返回值类型返回适当的零值
	if funcName == "Eq" {
		sb.WriteString("    return eq(x, y), nil\n")
	} else {
		if returnType == "bool" {
			sb.WriteString("    return false, fmt.Errorf(\"unsupported operator: %T %s %T\", x, \"")
		} else if returnType == "int" {
			sb.WriteString("    return 0, fmt.Errorf(\"unsupported operator: %T %s %T\", x, \"")
		} else {
			sb.WriteString("    var zero any\n")
			sb.WriteString("    return zero, fmt.Errorf(\"unsupported operator: %T %s %T\", x, \"")
		}
		sb.WriteString(operator)
		sb.WriteString("\", y)\n")
	}

	sb.WriteString("}\n")

	return sb.String()
}

func isComparisonOperation(op string) bool {
	return op == "==" || op == "<" || op == ">" || op == ">=" || op == "<=" || op == "!="
}

func isBitwiseOperation(op string) bool {
	return op == "&" || op == "|" || op == "^" || op == "%" || op == "<<" || op == ">>"
}

func isFloatAllowed(op string) bool {
	// 位运算不允许浮点数
	bitwiseOps := map[string]bool{"&": true, "|": true, "^": true, "%": true, "<<": true, ">>": true}
	return !bitwiseOps[op]
}

func isStringAllowed(op string) bool {
	// 字符串只支持连接和比较运算
	stringOps := map[string]bool{
		"+": true, "==": true, "!=": true,
		"<": true, ">": true, "<=": true, ">=": true,
	}
	return stringOps[op]
}

func genToFuncs() {
	// 定义要生成的所有 int 和 float 类型
	intTypes := []string{
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
	}

	floatTypes := []string{
		"float32", "float64",
	}

	var sb strings.Builder

	// 写入文件头部
	sb.WriteString("// Code generated by ./cmd/genop.go; DO NOT EDIT.\n")
	sb.WriteString("//go:generate go run ./cmd/genop.go \n")
	sb.WriteString("package gen\n\n")
	sb.WriteString("import \"fmt\"\n\n")

	// 为每个 int 类型生成转换函数
	for _, intType := range intTypes {
		genToFuc(&sb, intType, intTypes, floatTypes)
	}

	// 为每个 float 类型生成转换函数
	for _, floatType := range floatTypes {
		genToFuc(&sb, floatType, intTypes, floatTypes)
	}

	// 写入文件
	err := os.WriteFile("./gen/to.gen.go", []byte(sb.String()), 0644)
	if err != nil {
		panic(err)
	}

	fmt.Println("tofunc代码生成至: ./gen/to.gen.go")
}

func genToFuc(sb *strings.Builder, targetType string, intTypes, floatTypes []string) {
	tryToFunc := "TryTo" + strings.Title(targetType)
	funcName := "To" + strings.Title(targetType)
	sb.WriteString(fmt.Sprintf("func %s(value any) %s {\n", funcName, targetType))
	sb.WriteString(fmt.Sprintf("    if val, ok := %s(value); ok {\n", tryToFunc))
	sb.WriteString("        return val\n")
	sb.WriteString("    }\n")
	sb.WriteString(fmt.Sprintf("   panic(fmt.Sprintf(\"%s: unsupport %%T\", value))\n", funcName))
	sb.WriteString("}\n")

	sb.WriteString(fmt.Sprintf("\nfunc %s(value any) (%s, bool) {\n", tryToFunc, targetType))
	sb.WriteString("    switch v := value.(type) {\n")

	// 目标类型本身的 case
	sb.WriteString(fmt.Sprintf("    case %s:\n", targetType))
	sb.WriteString("        return v, true\n")

	// 所有 int 类型的 case
	for _, intType := range intTypes {
		if intType != targetType {
			sb.WriteString(fmt.Sprintf("    case %s:\n", intType))
			sb.WriteString(fmt.Sprintf("        return %s(v), true\n", targetType))
		}
	}

	// 所有 float 类型的 case
	for _, floatType := range floatTypes {
		if floatType != targetType {
			sb.WriteString(fmt.Sprintf("    case %s:\n", floatType))
			sb.WriteString(fmt.Sprintf("        return %s(v), true\n", targetType))
		}
	}

	// default 情况
	sb.WriteString("    default:\n")
	sb.WriteString(fmt.Sprintf("        var zero %s\n", targetType))
	sb.WriteString("        return zero, false\n")
	sb.WriteString("    }\n")
	sb.WriteString("}\n\n")
}
