package consts

//SliceLiteralConst is generated by optimizer of ArrayLiteral
// NOTE: can't change this const, copy it when write to
type SliceLiteralConst struct {
	Value []any
	Name  string
}

// MapLiteralConst is generated by optimizer of DictLiteral
// NOTE: can't change this const, copy it when write to
type MapLiteralConst struct {
	Map  map[ConstNode]*ConstNode
	Name string
}
