package consts

import (
	"fmt"
	"reflect"
)

//SliceLiteralConst is generated by optimizer of ArrayLiteral
// NOTE: can't change this const, copy it when write to
type SliceLiteralConst struct {
	Value []any
	Name  string
}

// MapLiteralConst is generated by optimizer of DictLiteral
// NOTE: can't change this const, copy it when write to
type MapLiteralConst struct {
	Map  map[any]any
	Name string
}

type FunctionConst struct {
	Name       string
	ParamCount int
	LocalCount int
	Addr       int // 函数入口地址, 在[]AllFuncs中的索引
	Code       []StackInstr
}

type StructConst struct {
	Name   string
	Fields []string
}

type Tuple struct {
	Values []any
	Num    int
}

type Iter struct {
	Obj   any // slice: reflect.Value, map: reflect.MapIter,int:int
	Index []any
	Cur   int
	Len   int
	Kind  string // map/slice
}

func (i Iter) Done() bool {
	return i.Cur >= i.Len
}

func (i Iter) Next() (iter1, iter2 any) {
	switch i.Kind {
	case "slice":
		iter1, iter2 = i.Cur, i.Obj.(reflect.Value).Index(i.Cur).Interface()
	case "map":
		mapIter := i.Obj.(*reflect.MapIter)
		iter1, iter2 = mapIter.Key().Interface(), mapIter.Value().Interface()
	case "int":
		iter1, iter2 = i.Cur, i.Cur
	default:
		panic(fmt.Sprintf("unexpected type %T for iter", i.Obj))
	}
	i.Cur++
	return
}
