package consts

import (
	"fmt"
	"strings"

	"github.com/antlr4-go/antlr/v4"
	"github.com/ycl2018/gs/gen"
)

type ConstNodeKind int

const (
	ConstNodeKindInt ConstNodeKind = iota
	ConstNodeKindFloat
	ConstNodeKindString
	ConstNodeKindMap
	ConstNodeKindList
	ConstNodeKindBool
)

func ToBoolValue(c *ConstNode) bool {
	switch c.Kind {
	case ConstNodeKindBool:
		return c.Value.(bool)
	default:
		panic(fmt.Sprintf("ToBoolValue: unexpected type %T", c))
	}
}

func ToStringValue(c *ConstNode) string {
	switch c.Kind {
	case ConstNodeKindString:
		return c.Value.(string)
	default:
		panic(fmt.Sprintf("ToStringValue: can't const constant kind: %v to string", c.Kind))
	}
}

func ToFloatValue(c *ConstNode) float64 {
	switch c.Kind {
	case ConstNodeKindInt:
		return float64(c.Value.(int))
	case ConstNodeKindFloat:
		return c.Value.(float64)
	default:
		panic(fmt.Sprintf("ToFloatValue: can't get float value for constant kind: %v", c.Kind))
	}
}

func ToIntValue(c *ConstNode) int {
	switch c.Kind {
	case ConstNodeKindInt:
		return c.Value.(int)
	case ConstNodeKindFloat:
		return int(c.Value.(float64))
	default:
		panic(fmt.Sprintf("ToIntValue: can't get integer value for constant kind: %v", c.Kind))
	}
}

func NewConstNode(kind ConstNodeKind, val any, token antlr.Token) *ConstNode {
	return &ConstNode{
		Kind:  kind,
		Value: val,
		token: token,
	}
}

// ConstNode is fake node, can only be generated by optimizer
// can be any type of [logicalAndExpr,comparisonExpr,addExpr,binExpr,mulExpr,powExpr,atom] for dynamic dispatch
type ConstNode struct {
	Kind  ConstNodeKind
	Value any
	token antlr.Token
}

func (c *ConstNode) IsAtomContext() {

}

func (c *ConstNode) AllAtom() []gen.IAtomContext {
	return []gen.IAtomContext{c}
}

func (c *ConstNode) Atom(i int) gen.IAtomContext {
	return c
}

func (c *ConstNode) AllMulOp() []gen.IMulOpContext {
	return []gen.IMulOpContext{}
}

func (c *ConstNode) MulOp(i int) gen.IMulOpContext {
	return nil
}

func (c *ConstNode) IsMulExprContext() {

}

func (c *ConstNode) AllMulExpr() []gen.IMulExprContext {
	return []gen.IMulExprContext{c}
}

func (c *ConstNode) MulExpr(i int) gen.IMulExprContext {
	return c
}

func (c *ConstNode) AllBitOp() []gen.IBitOpContext {
	return nil
}

func (c *ConstNode) BitOp(i int) gen.IBitOpContext {
	return nil
}

func (c *ConstNode) IsBinExprContext() {

}

func (c *ConstNode) AllBinExpr() []gen.IBinExprContext {
	return []gen.IBinExprContext{c}
}

func (c *ConstNode) BinExpr(i int) gen.IBinExprContext {
	return c
}

func (c *ConstNode) AllAddOp() []gen.IAddOpContext {
	return nil
}

func (c *ConstNode) AddOp(i int) gen.IAddOpContext {
	return nil
}

func (c *ConstNode) IsAddExprContext() {
}

func (c *ConstNode) AllAddExpr() []gen.IAddExprContext {
	return []gen.IAddExprContext{c}
}

func (c *ConstNode) AddExpr(i int) gen.IAddExprContext {
	return c
}

func (c *ConstNode) CompOp() gen.ICompOpContext {
	return nil
}

func (c *ConstNode) IsComparisonExprContext() {
}

func (c *ConstNode) SetException(exception antlr.RecognitionException) {

}

func (c *ConstNode) AddTokenNode(token antlr.Token) *antlr.TerminalNodeImpl {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) AddErrorNode(badToken antlr.Token) *antlr.ErrorNodeImpl {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) EnterRule(listener antlr.ParseTreeListener) {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) ExitRule(listener antlr.ParseTreeListener) {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) SetStart(token antlr.Token) {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) GetStart() antlr.Token {
	//TODO implement me
	return c.token
}

func (c *ConstNode) SetStop(token antlr.Token) {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) GetStop() antlr.Token {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) AddChild(child antlr.RuleContext) antlr.RuleContext {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) RemoveLastChild() {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) GetParser() antlr.Parser {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) AllComparisonExpr() []gen.IComparisonExprContext {
	return []gen.IComparisonExprContext{c}
}

func (c *ConstNode) ComparisonExpr(i int) gen.IComparisonExprContext {
	return c
}

func (c *ConstNode) AllAND() []antlr.TerminalNode {
	return nil
}

func (c *ConstNode) AND(i int) antlr.TerminalNode {
	return nil
}

func (c *ConstNode) IsLogicalAndExprContext() {
}

func (c *ConstNode) GetSourceInterval() antlr.Interval {
	//TODO implement me
	panic("implement me")
}

// can't visit
func (c *ConstNode) Accept(Visitor antlr.ParseTreeVisitor) interface{} {
	if v, ok := Visitor.(interface {
		VisitConstNode(v *ConstNode) interface{}
	}); ok {
		return v.VisitConstNode(c)
	}
	return nil
}

func (c *ConstNode) GetText() string {
	switch c.Kind {
	case ConstNodeKindBool:
		return fmt.Sprintf("%t", c.Value.(bool))
	case ConstNodeKindInt:
		return fmt.Sprintf("%d", c.Value.(int))
	case ConstNodeKindFloat:
		return fmt.Sprintf("%f", c.Value.(float64))
	case ConstNodeKindString:
		return fmt.Sprintf("%s", c.Value.(string))
	case ConstNodeKindMap:
		var sb strings.Builder
		sb.WriteString("{")
		for k, v := range c.Value.(map[ConstNode]*ConstNode) {
			sb.WriteString(k.GetText() + ":" + v.GetText())
		}
		sb.WriteString("}")
		return sb.String()
	case ConstNodeKindList:
		var sb strings.Builder
		sb.WriteString("[")
		for i, v := range c.Value.([]ConstNode) {
			sb.WriteString(v.GetText())
			if i < len(c.Value.([]ConstNode)) {
				sb.WriteString(",")
			}
		}
		sb.WriteString("]")
		return sb.String()
	default:
		return ""
	}
}

func (c *ConstNode) ToStringTree(strings []string, recognizer antlr.Recognizer) string {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) GetRuleContext() antlr.RuleContext {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) GetInvokingState() int {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) SetInvokingState(i int) {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) GetRuleIndex() int {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) IsEmpty() bool {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) GetAltNumber() int {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) SetAltNumber(altNumber int) {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) String(strings []string, context antlr.RuleContext) string {
	return fmt.Sprintf("%+v", c)
}

func (c *ConstNode) GetParent() antlr.Tree {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) SetParent(tree antlr.Tree) {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) GetPayload() interface{} {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) GetChild(i int) antlr.Tree {
	//TODO implement me
	panic("implement me")
}

func (c *ConstNode) GetChildCount() int {
	//TODO implement me
	return 0
}

func (c *ConstNode) GetChildren() []antlr.Tree {
	//TODO implement me
	return nil
}
